/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/MyStyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/detail`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownInputParams; } | { pathname: `/src/listado`; params?: Router.UnknownInputParams; } | { pathname: `/src/stackNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/MyStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/src/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/src/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownOutputParams; } | { pathname: `/src/listado`; params?: Router.UnknownOutputParams; } | { pathname: `/src/stackNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/MyStyles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/src/detail${`?${string}` | `#${string}` | ''}` | `/src/firebase${`?${string}` | `#${string}` | ''}` | `/src/headerPlayers${`?${string}` | `#${string}` | ''}` | `/src/listado${`?${string}` | `#${string}` | ''}` | `/src/stackNavigation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/MyStyles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/detail`; params?: Router.UnknownInputParams; } | { pathname: `/src/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/src/headerPlayers`; params?: Router.UnknownInputParams; } | { pathname: `/src/listado`; params?: Router.UnknownInputParams; } | { pathname: `/src/stackNavigation`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
